name: Release
on:
- push
jobs:
  pdfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: DeterminateSystems/determinate-nix-action@v3
    - uses: DeterminateSystems/magic-nix-cache-action@v13
    - run: nix develop --command make cv.pdf
    - uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        files: "*.pdf"
